
LOGIN="mkane"
SERVER_IP="192.168.56.110"
WORKER_IP="192.168.56.111"

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp-education/ubuntu-24-04"
  config.vm.box_version = "0.1.0"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.synced_folder ".", "/vagrant_shared"

  config.vm.define "#{LOGIN}S" do |server|
    server.vm.hostname = "#{LOGIN}S"
    server.vm.network "private_network", ip: SERVER_IP

    server.vm.provision "shell", inline: <<-SHELL

      IFACE=$(ip -o -4 addr list | grep #{SERVER_IP} | awk '{print $2}')
      curl -sfL https://get.k3s.io | \
        INSTALL_K3S_EXEC="--node-ip=#{SERVER_IP} --flannel-iface=$IFACE" \
        sh -

      sudo cat /var/lib/rancher/k3s/server/node-token > /vagrant_shared/token

      sudo chmod 644 /etc/rancher/k3s/k3s.yaml
      mkdir -p /home/vagrant/.kube
      sudo cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config
      sudo chown vagrant:vagrant /home/vagrant/.kube/config
    SHELL
  end

  config.vm.define "#{LOGIN}SW" do |worker|
    worker.vm.hostname = "#{LOGIN}SW"
    worker.vm.network "private_network", ip: WORKER_IP

    worker.vm.provision "shell", inline: <<-SHELL
      IFACE=$(ip -o -4 addr list | grep #{SERVER_IP} | awk '{print $2}')
      TOKEN=$(cat /vagrant_shared/token)

      curl -sfL https://get.k3s.io | \
        K3S_URL=https://192.168.56.110:6443 \
        K3S_TOKEN=$TOKEN \
        INSTALL_K3S_EXEC="--node-ip=192.168.56.111 --flannel-iface=$IFACE" \
        sh -
    SHELL
  end

end
